CREATE TABLE transaction_status_categories(
	id SERIAL PRIMARY KEY
	, name VARCHAR(255) NOT NULL UNIQUE
	, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
	, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)